module.exports={
    ".3gp":{appType:"video/3gpp",imgPath:"./images/mime_video.png"}
    ,".aab":{appType:"application/x-authoware-bin",imgPath:"./images/mime_others.png"}
    ,".aam":{appType:"application/x-authoware-map",imgPath:"./images/mime_others.png"}
    ,".aas":{appType:"application/x-authoware-seg",imgPath:"./images/mime_others.png"}
    ,".ai":{appType:"application/postscript",imgPath:"./images/mime_others.png"}
    ,".aif":{appType:"audio/x-aiff",imgPath:"./images/mime_others.png"}
    ,".aifc":{appType:"audio/x-aiff",imgPath:"./images/mime_others.png"}
    ,".aiff":{appType:"audio/x-aiff",imgPath:"./images/mime_others.png"}
    ,".als":{appType:"audio/X-Alpha5",imgPath:"./images/mime_others.png"}
    ,".amc":{appType:"application/x-mpeg",imgPath:"./images/mime_others.png"}
    ,".ani":{appType:"application/octet-stream",imgPath:"./images/mime_others.png"}
    ,".asc":{appType:"text/plain",imgPath:"./images/mime_text.png"}
    ,".asd":{appType:"application/astound",imgPath:"./images/mime_others.png"}
    ,".asf":{appType:"video/x-ms-asf",imgPath:"./images/mime_others.png"}
    ,".asn":{appType:"application/astound",imgPath:"./images/mime_others.png"}
    ,".asp":{appType:"application/x-asap",imgPath:"./images/mime_others.png"}
    ,".asx":{appType:"video/x-ms-asf",imgPath:"./images/mime_video.png"}
    ,".au":{appType:"audio/basic",imgPath:"./images/mime_aidop.png"}
    ,".avb":{appType:"application/octet-stream",imgPath:"./images/mime_others.png"}
    ,".avi":{appType:"video/x-msvideo",imgPath:"./images/mime_video.png"}
    ,".awb":{appType:"audio/amr-wb",imgPath:"./images/mime_others.png"}
    ,".bcpio":{appType:"application/x-bcpio",imgPath:"./images/mime_others.png"}
    ,".bin":{appType:"application/octet-stream",imgPath:"./images/mime_exe.png"}
    ,".bld":{appType:"application/bld",imgPath:"./images/mime_others.png"}
    ,".bld2":{appType:"application/bld2",imgPath:"./images/mime_others.png"}
    ,".bmp":{appType:"application/x-MS-bmp",imgPath:"./images/mime_image.png"}
    ,".bpk":{appType:"application/octet-stream",imgPath:"./images/mime_others.png"}
    ,".bz2":{appType:"application/x-bzip2",imgPath:"./images/mime_others.png"}
    ,".cal":{appType:"image/x-cals",imgPath:"./images/mime_image.png"}
    ,".ccn":{appType:"application/x-cnc",imgPath:"./images/mime_others.png"}
    ,".cco":{appType:"application/x-cocoa",imgPath:"./images/mime_others.png"}
    ,".cdf":{appType:"application/x-netcdf",imgPath:"./images/mime_others.png"}
    ,".cgi":{appType:"magnus-internal/cgi",imgPath:"./images/mime_others.png"}
    ,".chat":{appType:"application/x-chat",imgPath:"./images/mime_others.png"}
    ,".class":{appType:"application/octet-stream",imgPath:"./images/mime_others.png"}
    ,".clp":{appType:"application/x-msclip",imgPath:"./images/mime_others.png"}
    ,".cmx":{appType:"application/x-cmx",imgPath:"./images/mime_others.png"}
    ,".co":{appType:"application/x-cult3d-object",imgPath:"./images/mime_others.png"}
    ,".cod":{appType:"image/cis-cod",imgPath:"./images/mime_others.png"}
    ,".cpio":{appType:"application/x-cpio",imgPath:"./images/mime_others.png"}
    ,".cpt":{appType:"application/mac-compactpro",imgPath:"./images/mime_others.png"}
    ,".crd":{appType:"application/x-mscardfile",imgPath:"./images/mime_others.png"}
    ,".csh":{appType:"application/x-csh",imgPath:"./images/mime_others.png"}
    ,".csm":{appType:"chemical/x-csml",imgPath:"./images/mime_others.png"}
    ,".csml":{appType:"chemical/x-csml",imgPath:"./images/mime_others.png"}
    ,".css":{appType:"text/css",imgPath:"./images/mime_others.png"}
    ,".cur":{appType:"application/octet-stream",imgPath:"./images/mime_others.png"}
    ,".dcm":{appType:"x-lml/x-evm",imgPath:"./images/mime_others.png"}
    ,".dcr":{appType:"application/x-director",imgPath:"./images/mime_others.png"}
    ,".dcx":{appType:"image/x-dcx",imgPath:"./images/mime_others.png"}
    ,".dhtml":{appType:"text/html",imgPath:"./images/mime_others.png"}
    ,".dir":{appType:"application/x-director",imgPath:"./images/mime_others.png"}
    ,".dll":{appType:"application/octet-stream",imgPath:"./images/mime_others.png"}
    ,".dmg":{appType:"application/octet-stream",imgPath:"./images/mime_others.png"}
    ,".dms":{appType:"application/octet-stream",imgPath:"./images/mime_others.png"}
    ,".doc":{appType:"application/msword",imgPath:"./images/mime_word.png"}
    ,".docx":{appType:"application/msword",imgPath:"./images/mime_word.png"}
    ,".dot":{appType:"application/x-dot",imgPath:"./images/mime_word.png"}
    ,".dvi":{appType:"application/x-dvi",imgPath:"./images/mime_others.png"}
    ,".dwf":{appType:"drawing/x-dwf",imgPath:"./images/mime_others.png"}
    ,".dwg":{appType:"application/x-autocad",imgPath:"./images/mime_autocad.png"}
    ,".dxf":{appType:"application/x-autocad",imgPath:"./images/mime_others.png"}
    ,".dxr":{appType:"application/x-director",imgPath:"./images/mime_others.png"}
    ,".ebk":{appType:"application/x-expandedbook",imgPath:"./images/mime_others.png"}
    ,".emb":{appType:"chemical/x-embl-dl-nucleotide",imgPath:"./images/mime_others.png"}
    ,".embl":{appType:"chemical/x-embl-dl-nucleotide",imgPath:"./images/mime_others.png"}
    ,".eps":{appType:"application/postscript",imgPath:"./images/mime_others.png"}
    ,".eri":{appType:"image/x-eri",imgPath:"./images/mime_others.png"}
    ,".es":{appType:"audio/echospeech",imgPath:"./images/mime_others.png"}
    ,".esl":{appType:"audio/echospeech",imgPath:"./images/mime_others.png"}
    ,".etc":{appType:"application/x-earthtime",imgPath:"./images/mime_others.png"}
    ,".etx":{appType:"text/x-setext",imgPath:"./images/mime_others.png"}
    ,".evm":{appType:"x-lml/x-evm",imgPath:"./images/mime_others.png"}
    ,".evy":{appType:"application/x-envoy",imgPath:"./images/mime_others.png"}
    ,".exe":{appType:"application/octet-stream",imgPath:"./images/mime_exe.png"}
    ,".fh4":{appType:"image/x-freehand",imgPath:"./images/mime_others.png"}
    ,".fh5":{appType:"image/x-freehand",imgPath:"./images/mime_others.png"}
    ,".fhc":{appType:"image/x-freehand",imgPath:"./images/mime_others.png"}
    ,".fif":{appType:"image/fif",imgPath:"./images/mime_others.png"}
    ,".fm":{appType:"application/x-maker",imgPath:"./images/mime_others.png"}
    ,".fpx":{appType:"image/x-fpx",imgPath:"./images/mime_others.png"}
    ,".fvi":{appType:"video/isivideo",imgPath:"./images/mime_others.png"}
    ,".gau":{appType:"chemical/x-gaussian-input",imgPath:"./images/mime_others.png"}
    ,".gca":{appType:"application/x-gca-compressed",imgPath:"./images/mime_others.png"}
    ,".gdb":{appType:"x-lml/x-gdb",imgPath:"./images/mime_others.png"}
    ,".gif":{appType:"image/gif",imgPath:"./images/mime_image.png"}
    ,".gps":{appType:"application/x-gps",imgPath:"./images/mime_others.png"}
    ,".gtar":{appType:"application/x-gtar",imgPath:"./images/mime_others.png"}
    ,".gz":{appType:"application/x-gzip",imgPath:"./images/mime_others.png"}
    ,".hdf":{appType:"application/x-hdf",imgPath:"./images/mime_others.png"}
    ,".hdm":{appType:"text/x-hdml",imgPath:"./images/mime_others.png"}
    ,".hdml":{appType:"text/x-hdml",imgPath:"./images/mime_others.png"}
    ,".hlp":{appType:"application/winhlp",imgPath:"./images/mime_others.png"}
    ,".hqx":{appType:"application/mac-binhex40",imgPath:"./images/mime_others.png"}
    ,".htm":{appType:"text/html",imgPath:"./images/mime_web.png"}
    ,".html":{appType:"text/html",imgPath:"./images/mime_web.png"}
    ,".hts":{appType:"text/html",imgPath:"./images/mime_others.png"}
    ,".ice":{appType:"x-conference/x-cooltalk",imgPath:"./images/mime_others.png"}
    ,".ico":{appType:"application/octet-stream",imgPath:"./images/mime_image.png"}
    ,".ief":{appType:"image/ief",imgPath:"./images/mime_others.png"}
    ,".ifm":{appType:"image/gif",imgPath:"./images/mime_others.png"}
    ,".ifs":{appType:"image/ifs",imgPath:"./images/mime_others.png"}
    ,".imy":{appType:"audio/melody",imgPath:"./images/mime_others.png"}
    ,".ins":{appType:"application/x-NET-Install",imgPath:"./images/mime_others.png"}
    ,".ips":{appType:"application/x-ipscript",imgPath:"./images/mime_others.png"}
    ,".ipx":{appType:"application/x-ipix",imgPath:"./images/mime_others.png"}
    ,".it":{appType:"audio/x-mod",imgPath:"./images/mime_others.png"}
    ,".itz":{appType:"audio/x-mod",imgPath:"./images/mime_others.png"}
    ,".ivr":{appType:"i-world/i-vrml",imgPath:"./images/mime_others.png"}
    ,".j2k":{appType:"image/j2k",imgPath:"./images/mime_others.png"}
    ,".jad":{appType:"text/vnd.sun.j2me.app-descriptor",imgPath:"./images/mime_zip.png"}
    ,".jam":{appType:"application/x-jam",imgPath:"./images/mime_others.png"}
    ,".jar":{appType:"application/java-archive",imgPath:"./images/mime_zip.png"}
    ,".jnlp":{appType:"application/x-java-jnlp-file",imgPath:"./images/mime_others.png"}
    ,".jpe":{appType:"image/jpeg",imgPath:"./images/mime_image.png"}
    ,".jpeg":{appType:"image/jpeg",imgPath:"./images/mime_image.png"}
    ,".jpg":{appType:"image/jpeg",imgPath:"./images/mime_image.png"}
    ,".jpz":{appType:"image/jpeg",imgPath:"./images/mime_others.png"}
    ,".js":{appType:"application/x-javascript",imgPath:"./images/mime_code.png"}
    ,".jwc":{appType:"application/jwc",imgPath:"./images/mime_others.png"}
    ,".kjx":{appType:"application/x-kjx",imgPath:"./images/mime_others.png"}
    ,".lak":{appType:"x-lml/x-lak",imgPath:"./images/mime_others.png"}
    ,".latex":{appType:"application/x-latex",imgPath:"./images/mime_others.png"}
    ,".lcc":{appType:"application/fastman",imgPath:"./images/mime_others.png"}
    ,".lcl":{appType:"application/x-digitalloca",imgPath:"./images/mime_others.png"}
    ,".lcr":{appType:"application/x-digitalloca",imgPath:"./images/mime_others.png"}
    ,".lgh":{appType:"application/lgh",imgPath:"./images/mime_others.png"}
    ,".lha":{appType:"application/octet-stream",imgPath:"./images/mime_others.png"}
    ,".lml":{appType:"x-lml/x-lml",imgPath:"./images/mime_others.png"}
    ,".lmlpack":{appType:"x-lml/x-lmlpack",imgPath:"./images/mime_others.png"}
    ,".lsf":{appType:"video/x-ms-asf",imgPath:"./images/mime_others.png"}
    ,".lsx":{appType:"video/x-ms-asf",imgPath:"./images/mime_others.png"}
    ,".lzh":{appType:"application/x-lzh",imgPath:"./images/mime_others.png"}
    ,".m13":{appType:"application/x-msmediaview",imgPath:"./images/mime_others.png"}
    ,".m14":{appType:"application/x-msmediaview",imgPath:"./images/mime_others.png"}
    ,".m15":{appType:"audio/x-mod",imgPath:"./images/mime_others.png"}
    ,".m3u":{appType:"audio/x-mpegurl",imgPath:"./images/mime_others.png"}
    ,".m3url":{appType:"audio/x-mpegurl",imgPath:"./images/mime_others.png"}
    ,".ma1":{appType:"audio/ma1",imgPath:"./images/mime_others.png"}
    ,".ma2":{appType:"audio/ma2",imgPath:"./images/mime_others.png"}
    ,".ma3":{appType:"audio/ma3",imgPath:"./images/mime_others.png"}
    ,".ma5":{appType:"audio/ma5",imgPath:"./images/mime_others.png"}
    ,".man":{appType:"application/x-troff-man",imgPath:"./images/mime_others.png"}
    ,".map":{appType:"magnus-internal/imagemap",imgPath:"./images/mime_others.png"}
    ,".mbd":{appType:"application/mbedlet",imgPath:"./images/mime_others.png"}
    ,".mct":{appType:"application/x-mascot",imgPath:"./images/mime_others.png"}
    ,".mdb":{appType:"application/x-msaccess",imgPath:"./images/mime_others.png"}
    ,".mdz":{appType:"audio/x-mod",imgPath:"./images/mime_others.png"}
    ,".me":{appType:"application/x-troff-me",imgPath:"./images/mime_others.png"}
    ,".mel":{appType:"text/x-vmel",imgPath:"./images/mime_others.png"}
    ,".mi":{appType:"application/x-mif",imgPath:"./images/mime_others.png"}
    ,".mid":{appType:"audio/midi",imgPath:"./images/mime_others.png"}
    ,".midi":{appType:"audio/midi",imgPath:"./images/mime_others.png"}
    ,".mif":{appType:"application/x-mif",imgPath:"./images/mime_others.png"}
    ,".mil":{appType:"image/x-cals",imgPath:"./images/mime_others.png"}
    ,".mio":{appType:"audio/x-mio",imgPath:"./images/mime_others.png"}
    ,".mmf":{appType:"application/x-skt-lbs",imgPath:"./images/mime_others.png"}
    ,".mng":{appType:"video/x-mng",imgPath:"./images/mime_video.png"}
    ,".mny":{appType:"application/x-msmoney",imgPath:"./images/mime_others.png"}
    ,".moc":{appType:"application/x-mocha",imgPath:"./images/mime_others.png"}
    ,".mocha":{appType:"application/x-mocha",imgPath:"./images/mime_others.png"}
    ,".mod":{appType:"audio/x-mod",imgPath:"./images/mime_others.png"}
    ,".mof":{appType:"application/x-yumekara",imgPath:"./images/mime_others.png"}
    ,".mol":{appType:"chemical/x-mdl-molfile",imgPath:"./images/mime_others.png"}
    ,".mop":{appType:"chemical/x-mopac-input",imgPath:"./images/mime_others.png"}
    ,".mov":{appType:"video/quicktime",imgPath:"./images/mime_video.png"}
    ,".movie":{appType:"video/x-sgi-movie",imgPath:"./images/mime_video.png"}
    ,".mp2":{appType:"audio/x-mpeg",imgPath:"./images/mime_audio.png"}
    ,".mp3":{appType:"audio/x-mpeg",imgPath:"./images/mime_audio.png"}
    ,".mp4":{appType:"video/mp4",imgPath:"./images/mime_audio.png"}
    ,".mpc":{appType:"application/vnd.mpohun.certificate",imgPath:"./images/mime_others.png"}
    ,".mpe":{appType:"video/mpeg",imgPath:"./images/mime_video.png"}
    ,".mpeg":{appType:"video/mpeg",imgPath:"./images/mime_video.png"}
    ,".mpg":{appType:"video/mpeg",imgPath:"./images/mime_video.png"}
    ,".mpg4":{appType:"video/mp4",imgPath:"./images/mime_video.png"}
    ,".mpga":{appType:"audio/mpeg",imgPath:"./images/mime_others.png"}
    ,".mpn":{appType:"application/vnd.mophun.application",imgPath:"./images/mime_others.png"}
    ,".mpp":{appType:"application/vnd.ms-project",imgPath:"./images/mime_others.png"}
    ,".mps":{appType:"application/x-mapserver",imgPath:"./images/mime_others.png"}
    ,".mrl":{appType:"text/x-mrml",imgPath:"./images/mime_others.png"}
    ,".mrm":{appType:"application/x-mrm",imgPath:"./images/mime_others.png"}
    ,".ms":{appType:"application/x-troff-ms",imgPath:"./images/mime_others.png"}
    ,".mts":{appType:"application/metastream",imgPath:"./images/mime_others.png"}
    ,".mtx":{appType:"application/metastream",imgPath:"./images/mime_others.png"}
    ,".mtz":{appType:"application/metastream",imgPath:"./images/mime_others.png"}
    ,".mzv":{appType:"application/metastream",imgPath:"./images/mime_others.png"}
    ,".nar":{appType:"application/zip",imgPath:"./images/mime_others.png"}
    ,".nbmp":{appType:"image/nbmp",imgPath:"./images/mime_others.png"}
    ,".nc":{appType:"application/x-netcdf",imgPath:"./images/mime_others.png"}
    ,".ndb":{appType:"x-lml/x-ndb",imgPath:"./images/mime_others.png"}
    ,".ndwn":{appType:"application/ndwn",imgPath:"./images/mime_others.png"}
    ,".nif":{appType:"application/x-nif",imgPath:"./images/mime_others.png"}
    ,".nmz":{appType:"application/x-scream",imgPath:"./images/mime_others.png"}
    ,".nokia-op-logo":{appType:"image/vnd.nok-oplogo-color",imgPath:"./images/mime_others.png"}
    ,".npx":{appType:"application/x-netfpx",imgPath:"./images/mime_others.png"}
    ,".nsnd":{appType:"audio/nsnd",imgPath:"./images/mime_others.png"}
    ,".nva":{appType:"application/x-neva1",imgPath:"./images/mime_others.png"}
    ,".oda":{appType:"application/oda",imgPath:"./images/mime_others.png"}
    ,".oom":{appType:"application/x-AtlasMate-Plugin",imgPath:"./images/mime_others.png"}
    ,".pac":{appType:"audio/x-pac",imgPath:"./images/mime_others.png"}
    ,".pae":{appType:"audio/x-epac",imgPath:"./images/mime_others.png"}
    ,".pan":{appType:"application/x-pan",imgPath:"./images/mime_others.png"}
    ,".pbm":{appType:"image/x-portable-bitmap",imgPath:"./images/mime_others.png"}
    ,".pcx":{appType:"image/x-pcx",imgPath:"./images/mime_others.png"}
    ,".pda":{appType:"image/x-pda",imgPath:"./images/mime_others.png"}
    ,".pdb":{appType:"chemical/x-pdb",imgPath:"./images/mime_others.png"}
    ,".pdf":{appType:"application/pdf",imgPath:"./images/mime_others.png"}
    ,".pfr":{appType:"application/font-tdpfr",imgPath:"./images/mime_others.png"}
    ,".pgm":{appType:"image/x-portable-graymap",imgPath:"./images/mime_others.png"}
    ,".pict":{appType:"image/x-pict",imgPath:"./images/mime_others.png"}
    ,".pm":{appType:"application/x-perl",imgPath:"./images/mime_others.png"}
    ,".pmd":{appType:"application/x-pmd",imgPath:"./images/mime_others.png"}
    ,".png":{appType:"image/png",imgPath:"./images/mime_others.png"}
    ,".pnm":{appType:"image/x-portable-anymap",imgPath:"./images/mime_others.png"}
    ,".pnz":{appType:"image/png",imgPath:"./images/mime_others.png"}
    ,".pot":{appType:"application/vnd.ms-powerpoint",imgPath:"./images/mime_others.png"}
    ,".ppm":{appType:"image/x-portable-pixmap",imgPath:"./images/mime_others.png"}
    ,".pps":{appType:"application/vnd.ms-powerpoint",imgPath:"./images/mime_others.png"}
    ,".ppt":{appType:"application/vnd.ms-powerpoint",imgPath:"./images/mime_others.png"}
    ,".pptx":{appType:"application/vnd.ms-powerpoint",imgPath:"./images/mime_others.png"}
    ,".pqf":{appType:"application/x-cprplayer",imgPath:"./images/mime_others.png"}
    ,".pqi":{appType:"application/cprplayer",imgPath:"./images/mime_others.png"}
    ,".prc":{appType:"application/x-prc",imgPath:"./images/mime_others.png"}
    ,".proxy":{appType:"application/x-ns-proxy-autoconfig",imgPath:"./images/mime_others.png"}
    ,".ps":{appType:"application/postscript",imgPath:"./images/mime_others.png"}
    ,".ptlk":{appType:"application/listenup",imgPath:"./images/mime_others.png"}
    ,".pub":{appType:"application/x-mspublisher",imgPath:"./images/mime_others.png"}
    ,".pvx":{appType:"video/x-pv-pvx",imgPath:"./images/mime_others.png"}
    ,".qcp":{appType:"audio/vnd.qcelp",imgPath:"./images/mime_others.png"}
    ,".qt":{appType:"video/quicktime",imgPath:"./images/mime_others.png"}
    ,".qti":{appType:"image/x-quicktime",imgPath:"./images/mime_others.png"}
    ,".qtif":{appType:"image/x-quicktime",imgPath:"./images/mime_others.png"}
    ,".r3t":{appType:"text/vnd.rn-realtext3d",imgPath:"./images/mime_others.png"}
    ,".ra":{appType:"audio/x-pn-realaudio",imgPath:"./images/mime_others.png"}
    ,".ram":{appType:"audio/x-pn-realaudio",imgPath:"./images/mime_others.png"}
    ,".rar":{appType:"application/x-rar-compressed",imgPath:"./images/mime_others.png"}
    ,".ras":{appType:"image/x-cmu-raster",imgPath:"./images/mime_others.png"}
    ,".rdf":{appType:"application/rdf+xml",imgPath:"./images/mime_others.png"}
    ,".rf":{appType:"image/vnd.rn-realflash",imgPath:"./images/mime_others.png"}
    ,".rgb":{appType:"image/x-rgb",imgPath:"./images/mime_others.png"}
    ,".rlf":{appType:"application/x-richlink",imgPath:"./images/mime_others.png"}
    ,".rm":{appType:"audio/x-pn-realaudio",imgPath:"./images/mime_others.png"}
    ,".rmf":{appType:"audio/x-rmf",imgPath:"./images/mime_others.png"}
    ,".rmm":{appType:"audio/x-pn-realaudio",imgPath:"./images/mime_others.png"}
    ,".rmvb":{appType:"audio/x-pn-realaudio",imgPath:"./images/mime_others.png"}
    ,".rnx":{appType:"application/vnd.rn-realplayer",imgPath:"./images/mime_others.png"}
    ,".roff":{appType:"application/x-troff",imgPath:"./images/mime_others.png"}
    ,".rp":{appType:"image/vnd.rn-realpix",imgPath:"./images/mime_others.png"}
    ,".rpm":{appType:"audio/x-pn-realaudio-plugin",imgPath:"./images/mime_others.png"}
    ,".rt":{appType:"text/vnd.rn-realtext",imgPath:"./images/mime_others.png"}
    ,".rte":{appType:"x-lml/x-gps",imgPath:"./images/mime_others.png"}
    ,".rtf":{appType:"application/rtf",imgPath:"./images/mime_others.png"}
    ,".rtg":{appType:"application/metastream",imgPath:"./images/mime_others.png"}
    ,".rtx":{appType:"text/richtext",imgPath:"./images/mime_others.png"}
    ,".rv":{appType:"video/vnd.rn-realvideo",imgPath:"./images/mime_others.png"}
    ,".rwc":{appType:"application/x-rogerwilco",imgPath:"./images/mime_others.png"}
    ,".s3m":{appType:"audio/x-mod",imgPath:"./images/mime_others.png"}
    ,".s3z":{appType:"audio/x-mod",imgPath:"./images/mime_others.png"}
    ,".sca":{appType:"application/x-supercard",imgPath:"./images/mime_others.png"}
    ,".scd":{appType:"application/x-msschedule",imgPath:"./images/mime_others.png"}
    ,".sdf":{appType:"application/e-score",imgPath:"./images/mime_others.png"}
    ,".sea":{appType:"application/x-stuffit",imgPath:"./images/mime_others.png"}
    ,".sgm":{appType:"text/x-sgml",imgPath:"./images/mime_others.png"}
    ,".sgml":{appType:"text/x-sgml",imgPath:"./images/mime_others.png"}
    ,".sh":{appType:"application/x-sh",imgPath:"./images/mime_others.png"}
    ,".shar":{appType:"application/x-shar",imgPath:"./images/mime_others.png"}
    ,".shtml":{appType:"magnus-internal/parsed-html",imgPath:"./images/mime_others.png"}
    ,".shw":{appType:"application/presentations",imgPath:"./images/mime_others.png"}
    ,".si6":{appType:"image/si6",imgPath:"./images/mime_others.png"}
    ,".si7":{appType:"image/vnd.stiwap.sis",imgPath:"./images/mime_others.png"}
    ,".si9":{appType:"image/vnd.lgtwap.sis",imgPath:"./images/mime_others.png"}
    ,".sis":{appType:"application/vnd.symbian.install",imgPath:"./images/mime_others.png"}
    ,".sit":{appType:"application/x-stuffit",imgPath:"./images/mime_others.png"}
    ,".skd":{appType:"application/x-Koan",imgPath:"./images/mime_others.png"}
    ,".skm":{appType:"application/x-Koan",imgPath:"./images/mime_others.png"}
    ,".skp":{appType:"application/x-Koan",imgPath:"./images/mime_others.png"}
    ,".skt":{appType:"application/x-Koan",imgPath:"./images/mime_others.png"}
    ,".slc":{appType:"application/x-salsa",imgPath:"./images/mime_others.png"}
    ,".smd":{appType:"audio/x-smd",imgPath:"./images/mime_others.png"}
    ,".smi":{appType:"application/smil",imgPath:"./images/mime_others.png"}
    ,".smil":{appType:"application/smil",imgPath:"./images/mime_others.png"}
    ,".smp":{appType:"application/studiom",imgPath:"./images/mime_others.png"}
    ,".smz":{appType:"audio/x-smd",imgPath:"./images/mime_others.png"}
    ,".snd":{appType:"audio/basic",imgPath:"./images/mime_others.png"}
    ,".spc":{appType:"text/x-speech",imgPath:"./images/mime_others.png"}
    ,".spl":{appType:"application/futuresplash",imgPath:"./images/mime_others.png"}
    ,".spr":{appType:"application/x-sprite",imgPath:"./images/mime_others.png"}
    ,".sprite":{appType:"application/x-sprite",imgPath:"./images/mime_others.png"}
    ,".spt":{appType:"application/x-spt",imgPath:"./images/mime_others.png"}
    ,".src":{appType:"application/x-wais-source",imgPath:"./images/mime_others.png"}
    ,".stk":{appType:"application/hyperstudio",imgPath:"./images/mime_others.png"}
    ,".stm":{appType:"audio/x-mod",imgPath:"./images/mime_others.png"}
    ,".sv4cpio":{appType:"application/x-sv4cpio",imgPath:"./images/mime_others.png"}
    ,".sv4crc":{appType:"application/x-sv4crc",imgPath:"./images/mime_others.png"}
    ,".svf":{appType:"image/vnd",imgPath:"./images/mime_others.png"}
    ,".svg":{appType:"image/svg-xml",imgPath:"./images/mime_others.png"}
    ,".svh":{appType:"image/svh",imgPath:"./images/mime_others.png"}
    ,".svr":{appType:"x-world/x-svr",imgPath:"./images/mime_others.png"}
    ,".swf":{appType:"application/x-shockwave-flash",imgPath:"./images/mime_others.png"}
    ,".swfl":{appType:"application/x-shockwave-flash",imgPath:"./images/mime_others.png"}
    ,".t":{appType:"application/x-troff",imgPath:"./images/mime_others.png"}
    ,".tad":{appType:"application/octet-stream",imgPath:"./images/mime_others.png"}
    ,".talk":{appType:"text/x-speech",imgPath:"./images/mime_others.png"}
    ,".tar":{appType:"application/x-tar",imgPath:"./images/mime_others.png"}
    ,".taz":{appType:"application/x-tar",imgPath:"./images/mime_others.png"}
    ,".tbp":{appType:"application/x-timbuktu",imgPath:"./images/mime_others.png"}
    ,".tbt":{appType:"application/x-timbuktu",imgPath:"./images/mime_others.png"}
    ,".tcl":{appType:"application/x-tcl",imgPath:"./images/mime_others.png"}
    ,".tex":{appType:"application/x-tex",imgPath:"./images/mime_others.png"}
    ,".texi":{appType:"application/x-texinfo",imgPath:"./images/mime_others.png"}
    ,".texinfo":{appType:"application/x-texinfo",imgPath:"./images/mime_others.png"}
    ,".tgz":{appType:"application/x-tar",imgPath:"./images/mime_others.png"}
    ,".thm":{appType:"application/vnd.eri.thm",imgPath:"./images/mime_others.png"}
    ,".tif":{appType:"image/tiff",imgPath:"./images/mime_others.png"}
    ,".tiff":{appType:"image/tiff",imgPath:"./images/mime_others.png"}
    ,".tki":{appType:"application/x-tkined",imgPath:"./images/mime_others.png"}
    ,".tkined":{appType:"application/x-tkined",imgPath:"./images/mime_others.png"}
    ,".toc":{appType:"application/toc",imgPath:"./images/mime_others.png"}
    ,".toy":{appType:"image/toy",imgPath:"./images/mime_others.png"}
    ,".tr":{appType:"application/x-troff",imgPath:"./images/mime_others.png"}
    ,".trk":{appType:"x-lml/x-gps",imgPath:"./images/mime_others.png"}
    ,".trm":{appType:"application/x-msterminal",imgPath:"./images/mime_others.png"}
    ,".tsi":{appType:"audio/tsplayer",imgPath:"./images/mime_others.png"}
    ,".tsp":{appType:"application/dsptype",imgPath:"./images/mime_others.png"}
    ,".tsv":{appType:"text/tab-separated-values",imgPath:"./images/mime_others.png"}
    ,".tsv":{appType:"text/tab-separated-values",imgPath:"./images/mime_others.png"}
    ,".ttf":{appType:"application/octet-stream",imgPath:"./images/mime_others.png"}
    ,".ttz":{appType:"application/t-time",imgPath:"./images/mime_others.png"}
    ,".txt":{appType:"text/plain",imgPath:"./images/mime_others.png"}
    ,".ult":{appType:"audio/x-mod",imgPath:"./images/mime_others.png"}
    ,".ustar":{appType:"application/x-ustar",imgPath:"./images/mime_others.png"}
    ,".uu":{appType:"application/x-uuencode",imgPath:"./images/mime_others.png"}
    ,".uue":{appType:"application/x-uuencode",imgPath:"./images/mime_others.png"}
    ,".vcd":{appType:"application/x-cdlink",imgPath:"./images/mime_others.png"}
    ,".vcf":{appType:"text/x-vcard",imgPath:"./images/mime_others.png"}
    ,".vdo":{appType:"video/vdo",imgPath:"./images/mime_others.png"}
    ,".vib":{appType:"audio/vib",imgPath:"./images/mime_others.png"}
    ,".viv":{appType:"video/vivo",imgPath:"./images/mime_others.png"}
    ,".vivo":{appType:"video/vivo",imgPath:"./images/mime_others.png"}
    ,".vmd":{appType:"application/vocaltec-media-desc",imgPath:"./images/mime_others.png"}
    ,".vmf":{appType:"application/vocaltec-media-file",imgPath:"./images/mime_others.png"}
    ,".vmi":{appType:"application/x-dreamcast-vms-info",imgPath:"./images/mime_others.png"}
    ,".vms":{appType:"application/x-dreamcast-vms",imgPath:"./images/mime_others.png"}
    ,".vox":{appType:"audio/voxware",imgPath:"./images/mime_others.png"}
    ,".vqe":{appType:"audio/x-twinvq-plugin",imgPath:"./images/mime_others.png"}
    ,".vqf":{appType:"audio/x-twinvq",imgPath:"./images/mime_others.png"}
    ,".vql":{appType:"audio/x-twinvq",imgPath:"./images/mime_others.png"}
    ,".vre":{appType:"x-world/x-vream",imgPath:"./images/mime_others.png"}
    ,".vrml":{appType:"x-world/x-vrml",imgPath:"./images/mime_others.png"}
    ,".vrt":{appType:"x-world/x-vrt",imgPath:"./images/mime_others.png"}
    ,".vrw":{appType:"x-world/x-vream",imgPath:"./images/mime_others.png"}
    ,".vts":{appType:"workbook/formulaone",imgPath:"./images/mime_others.png"}
    ,".wav":{appType:"audio/x-wav",imgPath:"./images/mime_others.png"}
    ,".wax":{appType:"audio/x-ms-wax",imgPath:"./images/mime_others.png"}
    ,".wbmp":{appType:"image/vnd.wap.wbmp",imgPath:"./images/mime_others.png"}
    ,".web":{appType:"application/vnd.xara",imgPath:"./images/mime_others.png"}
    ,".wi":{appType:"image/wavelet",imgPath:"./images/mime_others.png"}
    ,".wis":{appType:"application/x-InstallShield",imgPath:"./images/mime_others.png"}
    ,".wm":{appType:"video/x-ms-wm",imgPath:"./images/mime_others.png"}
    ,".wma":{appType:"audio/x-ms-wma",imgPath:"./images/mime_others.png"}
    ,".wmd":{appType:"application/x-ms-wmd",imgPath:"./images/mime_others.png"}
    ,".wmf":{appType:"application/x-msmetafile",imgPath:"./images/mime_others.png"}
    ,".wml":{appType:"text/vnd.wap.wml",imgPath:"./images/mime_others.png"}
    ,".wmlc":{appType:"application/vnd.wap.wmlc",imgPath:"./images/mime_others.png"}
    ,".wmls":{appType:"text/vnd.wap.wmlscript",imgPath:"./images/mime_others.png"}
    ,".wmlsc":{appType:"application/vnd.wap.wmlscriptc",imgPath:"./images/mime_others.png"}
    ,".wmlscript":{appType:"text/vnd.wap.wmlscript",imgPath:"./images/mime_others.png"}
    ,".wmv":{appType:"audio/x-ms-wmv",imgPath:"./images/mime_others.png"}
    ,".wmx":{appType:"video/x-ms-wmx",imgPath:"./images/mime_others.png"}
    ,".wmz":{appType:"application/x-ms-wmz",imgPath:"./images/mime_others.png"}
    ,".wpng":{appType:"image/x-up-wpng",imgPath:"./images/mime_others.png"}
    ,".wpt":{appType:"x-lml/x-gps",imgPath:"./images/mime_others.png"}
    ,".wri":{appType:"application/x-mswrite",imgPath:"./images/mime_others.png"}
    ,".wrl":{appType:"x-world/x-vrml",imgPath:"./images/mime_others.png"}
    ,".wrz":{appType:"x-world/x-vrml",imgPath:"./images/mime_others.png"}
    ,".ws":{appType:"text/vnd.wap.wmlscript",imgPath:"./images/mime_others.png"}
    ,".wsc":{appType:"application/vnd.wap.wmlscriptc",imgPath:"./images/mime_others.png"}
    ,".wv":{appType:"video/wavelet",imgPath:"./images/mime_others.png"}
    ,".wvx":{appType:"video/x-ms-wvx",imgPath:"./images/mime_others.png"}
    ,".wxl":{appType:"application/x-wxl",imgPath:"./images/mime_others.png"}
    ,".x-gzip":{appType:"application/x-gzip",imgPath:"./images/mime_others.png"}
    ,".xar":{appType:"application/vnd.xara",imgPath:"./images/mime_others.png"}
    ,".xbm":{appType:"image/x-xbitmap",imgPath:"./images/mime_others.png"}
    ,".xdm":{appType:"application/x-xdma",imgPath:"./images/mime_others.png"}
    ,".xdma":{appType:"application/x-xdma",imgPath:"./images/mime_others.png"}
    ,".xdw":{appType:"application/vnd.fujixerox.docuworks",imgPath:"./images/mime_others.png"}
    ,".xht":{appType:"application/xhtml+xml",imgPath:"./images/mime_others.png"}
    ,".xhtm":{appType:"application/xhtml+xml",imgPath:"./images/mime_others.png"}
    ,".xhtml":{appType:"application/xhtml+xml",imgPath:"./images/mime_others.png"}
    ,".xla":{appType:"application/vnd.ms-excel",imgPath:"./images/mime_others.png"}
    ,".xlc":{appType:"application/vnd.ms-excel",imgPath:"./images/mime_others.png"}
    ,".xll":{appType:"application/x-excel",imgPath:"./images/mime_others.png"}
    ,".xlm":{appType:"application/vnd.ms-excel",imgPath:"./images/mime_others.png"}
    ,".xls":{appType:"application/vnd.ms-excel",imgPath:"./images/mime_others.png"}
    ,".xlsx":{appType:"application/vnd.ms-excel",imgPath:"./images/mime_others.png"}
    ,".xlt":{appType:"application/vnd.ms-excel",imgPath:"./images/mime_others.png"}
    ,".xlw":{appType:"application/vnd.ms-excel",imgPath:"./images/mime_others.png"}
    ,".xm":{appType:"audio/x-mod",imgPath:"./images/mime_others.png"}
    ,".xml":{appType:"text/xml",imgPath:"./images/mime_others.png"}
    ,".xmz":{appType:"audio/x-mod",imgPath:"./images/mime_others.png"}
    ,".xpi":{appType:"application/x-xpinstall",imgPath:"./images/mime_others.png"}
    ,".xpm":{appType:"image/x-xpixmap",imgPath:"./images/mime_others.png"}
    ,".xsit":{appType:"text/xml",imgPath:"./images/mime_others.png"}
    ,".xsl":{appType:"text/xml",imgPath:"./images/mime_others.png"}
    ,".xul":{appType:"text/xul",imgPath:"./images/mime_others.png"}
    ,".xwd":{appType:"image/x-xwindowdump",imgPath:"./images/mime_others.png"}
    ,".xyz":{appType:"chemical/x-pdb",imgPath:"./images/mime_others.png"}
    ,".yz1":{appType:"application/x-yz1",imgPath:"./images/mime_others.png"}
    ,".z":{appType:"application/x-compress",imgPath:"./images/mime_others.png"}
    ,".zac":{appType:"application/x-zaurus-zac",imgPath:"./images/mime_others.png"}
    ,".zip":{appType:"application/zip",imgPath:"./images/mime_zip.png"}
    ,"unknown":{appType:"unknown",imgPath:"./images/mime_known.png"}

}